type Problem {
  title: String!
  prompt: String!
  author: String!
  code: String!
  solutions: [Solution] @relation
}

type Solution {
  author: String!
  code: String!
  problem: Problem
}

type Query {
  allProblems: [Problem!]
  allSolutions: [Solution!]
}
